site_name: Rohini Muralidharan
site_description: This is a profile page.
site_url: https://rohinimuralidharan.com
theme:
  name: material
  features:
    - navigation.tabs

  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: amber
      accent: indigo

    # Light Mode
    - scheme: teal
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
plugins:
  - search
  - blog:
      blog_dir: .
      post_url_format: "{slug}"
  
#  - git-revision-date-localized:
#      fallback_to_build_date: false
#      type: date
#      enable_creation_date: true
#      enabled: true

  # - git-committers:
  #    repository: https://github.com/rohinimuralidharan/mynewprofile/
  #    branch: main
  #    token: !ENV GH_TOKEN
  #    enabled: true

  - tags:

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/rohinimuralidharan/
    - icon: fontawesome/brands/github
      link: https://github.com/rohinimuralidharan
  static_templates:
    - assets/ai-troubleshooter.html

    

nav:
  - About Me: overview.html
  - Blogs:
      - Conversational AI: posts/content_gtm_blog.md
      - Prompting Strategy: posts/prompting_technique_blog.md
  - Smart Support: ai-support.md

  
  
extra_css:
  - styles/profile.css  
    